# by SocialMoods

# _________             .__       .__      _____                    .___
# /   _____/ ____   ____ |__|____  |  |    /     \   ____   ____   __| _/______
# \_____  \ /  _ \_/ ___\|  \__  \ |  |   /  \ /  \ /  _ \ /  _ \ / __ |/  ___/
# /        (  <_> )  \___|  |/ __ \|  |__/    Y    (  <_> |  <_> ) /_/ |\___ \
# /_______  /\____/ \___  >__(____  /____/\____|__  /\____/ \____/\____ /____  >
# \/            \/        \/              \/                   \/    \/

# Плагин делался специально для SkyStudio

# Список разрешенных версий
versions:
  - "1.21.0"

# Сообщение при кике игрока
kick-message: "У вас несовместивая версия!"
